# Die Upload-APIs lassen höchstens 100 MiB pro gescannter Datei zu.
LogFile /var/log/clamav/clamd.log
LogTime yes
LocalSocket /tmp/clamd.sock
TCPSocket 3310
User clamav
DatabaseDirectory /var/lib/clamav
StreamMaxLength 100M
MaxFileSize 100M
MaxScanSize 400M
MaxRecursion 17
MaxFiles 10000
AlertExceedsMax yes
MaxThreads 2
MaxQueue 16
ReadTimeout 120
CommandReadTimeout 30
